# Generated by Django 5.1 on 2024-08-30 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_api", "0002_dblinestring_rename_point_dbpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
            ],
        ),
    ]
